# Generated by Django 3.2.5 on 2021-07-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alphacoe2', models.CharField(max_length=2)),
                ('alphacode3', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('flag', models.URLField(max_length=255)),
                ('neighbouring', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=12)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timezones', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso639_1', models.CharField(max_length=10)),
                ('iso639_2', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('nativeName', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='core.country')),
            ],
        ),
    ]
