# Generated by Django 3.2.5 on 2021-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_language_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='alphacoe2',
            new_name='alphacode2',
        ),
        migrations.AlterField(
            model_name='language',
            name='iso639_2',
            field=models.CharField(max_length=3),
        ),
    ]
