# Generated by Django 3.2.5 on 2021-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210731_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='neighbours',
            field=models.ManyToManyField(related_name='_core_country_neighbours_+', to='core.Country'),
        ),
    ]
